version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd server
      - npm install
      - cd ../client
      - npm install
      

  build:
    commands:
      - npm run build

artifacts:
  files:
    - appspec.yml
    - scripts/**
    - client/**/**
    - server/**/**